# Generated by Django 5.2.8 on 2025-11-25 07:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('event_name', models.CharField(max_length=200)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('forecast', models.CharField(blank=True, max_length=50)),
                ('previous', models.CharField(blank=True, max_length=50)),
                ('actual', models.CharField(blank=True, max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('is_notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='api_cacheen_key_aa05cd_idx'), models.Index(fields=['expires_at'], name='api_cacheen_expires_612f45_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pair', 'timeframe', 'timestamp'], name='api_marketd_pair_97c000_idx')],
                'unique_together': {('pair', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.IntegerField(default=1)),
                ('model_data', models.BinaryField(blank=True, null=True)),
                ('accuracy', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('trades_trained_on', models.IntegerField(default=0)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('training_metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_loss_pips', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=10)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('strategy_used', models.CharField(blank=True, max_length=100)),
                ('ml_prediction', models.FloatField(blank=True, null=True)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('technical_signals', models.JSONField(blank=True, default=dict)),
                ('capital_api_deal_id', models.CharField(blank=True, max_length=100)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=False)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('current_capital', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('forex_limit_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('gold_limit_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('last_ai_toggle', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('best_trade', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('worst_trade', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_trade_duration', models.DurationField(blank=True, null=True)),
                ('strategy_breakdown', models.JSONField(blank=True, default=dict)),
                ('pair_breakdown', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('market_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.marketdata')),
            ],
            options={
                'unique_together': {('market_data', 'indicator_name')},
            },
        ),
    ]
