# Generated by Django 5.2.8 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='pair',
            field=models.CharField(default='ALL', max_length=20),
        ),
    ]
